### ISSUE TITLE
Missing CMakeLists.txt files

### ISSUE THREAD

**Issue by jprotze** [rutgers-apl/omp-racer#1]
According to the README, `omp-racer/src/inst_pass/with_location_info` should be copied to `llvm-project/llvm/lib/Transforms/DataAnnotation` (Transforms is misspelled in the README)

cmake fails with:
```
CMake Error at lib/Transforms/CMakeLists.txt:12 (add_subdirectory):
  The source directory

    lib/Transforms/DataAnnotation

  does not contain a CMakeLists.txt file.
```

**Comment by nbushehri** [comment]
Thank you for pointing out this issue. It has been fixed in the latest commit.
